### PR TITLE
miscellaneous build fixes + update C dependencies

### PR DESCRIPTION
**Pull request by benoitc**
this change brings the following:

* build with REBAR 3 using a makefile
* fix build on Linux
* fix build on freebsd
* latest version f queue.h, tree.h and uthash.h improving support of CLANG

Would be good to have a new version with it on hex.pm.

### CODE REVIEW

**Comment by Licenser** [comment]
Hmm compiling this fails for me with a lot of the following errors:

```
/data/e2qc/c_src/nif.c:162:13: warning: no previous prototype for 'atom_tree_RB_INSERT_COLOR' [-Wmissing-prototypes]
 RB_GENERATE(atom_tree, atom_node, entry, atom_tree_cmp);
```

**Comment by benoitc** [comment]
it always had for me. It's harmless IMO and can be disabled by removing the `-Wmissing_prototype`. I will see if i can remove them in a later version.

**Comment by Licenser** [comment]
Oh damn sorry, I am a bit tired, I read the gcc output as errors. You're right it's just a warning should not be a issue :)

**Comment by Licenser** [comment]
published as 1.2.0

**Comment by benoitc** [comment]
thanks!

**Comment by Licenser** [comment]
thank you :)

**Pull request merged**
